### ISSUE TITLE
Rotating a bitmap without rotating the rest of the display list

### ISSUE THREAD

**Issue by grailler** [MatrixOrbital/Eve-School#1]
Hi,

Thank you so much for this useful library! I am trying to create my own loading animation. I intend to rotate a bitmap and even write some display text in the middle. My problem is when I rotate the bitmap, I am rotating everything that is added beyond that point on the display list

` FT813Q_Write_32_inc(RAM_CMD + cmdOffset, (DL_COLOR_RGB | WHITE));
  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, BEGIN(BITMAPS));
  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, BITMAP_HANDLE(Reference));
  //LoadIdentity();
  // Rotating matrix here
  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, CMD_ROTATE);
  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, 10 * 65536 / 360);

  // setting matrix
  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, CMD_SETMATRIX);

  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, (DL_VERTEX2F | (Xloc << 15) | Yloc));
  FT813Q_Write_32_inc(RAM_CMD + cmdOffset, END());`

Then if I write text here anywhere on the screen, it will be rotated as well.. I was kind of hoping the END() would put a end to the bitmap rotation. Any tip ? 
Thanks

**Comment by TharnLago** [comment]
Honestly, I have not done many things like this, but it is no surprise 
to me that Eve acts in ways you would not expect.  Truly, the manual 
says that it should affect "the next bitmap" and that implies that it 
will not affect further bitmaps.  I believe, though, that all bitmaps 
are probably affected by the current matrix (and "fonts" are definitely 
bitmaps from Eves perspective).

I would try CMD_LOADIDENTITY - 5.49 - BT81x Programmers Manual.  This 
should reset your matrix for further bitmaps.

Let me know what happens.  If it doesn't work, I will try again.

**Comment by grailler** [comment]
Hi TharnLago thanks for the quick answer, you were right! And you must set matrix again after that.
To sum up here what needs to be done:
`
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, (DL_COLOR_RGB | WHITE));
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, BEGIN(BITMAPS));
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, BITMAP_HANDLE(Reference));

// Rotating matrix here
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, CMD_ROTATE);
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, 10 * 65536 / 360);
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, CMD_SETMATRIX);

//place it
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, (DL_VERTEX2F | (Xloc << 15) | Yloc));

// reset matrix
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, CMD_LOADIDENTITY);
FT813Q_Write_32_inc(RAM_CMD + cmdOffset, CMD_SETMATRIX);

// NOW write some stuff here and it won't be rotated anymore!
``
Thanks again!
